//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef NFLVGL_H
#define NFLVGL_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_NFLvgl_NFLvgl_Lvgl
{
    NANOCLR_NATIVE_DECLARE(NativeInitDisplay___STATIC__VOID);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NFLvgl;

#endif // NFLVGL_H
