//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "NFLvgl.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_NFLvgl_NFLvgl_Lvgl::NativeInitDisplay___STATIC__VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NFLvgl =
{
    "NFLvgl",
    0xFDC8AD67,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
