//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "NFLvgl.h"
#include "NFLvgl_NFLvgl_Lvgl.h"

using namespace NFLvgl::NFLvgl;


HRESULT Library_NFLvgl_NFLvgl_Lvgl::NativeInitDisplay___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        Lvgl::NativeInitDisplay(  hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}
